version: '3'
services:

  php:
    container_name: test-box-php
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ./src:/var/www/test-box
    restart: unless-stopped
    ports:
      - 8000:8000
  db:
    container_name: test-box-sqlite
    image: nouchka/sqlite3:latest
    stdin_open: true    
    tty: true    
    volumes:      
      - ./src/data/:/root/db/
    restart: unless-stopped
